version: "3.7"

services:
  backend:
    image: lets-chat-backend
    container_name: lets-chat-backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    ports:
      - 5001:5001
    networks:
      - test
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.2.0-bionic
    container_name: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - db-data:/data/db
    networks:
      - test

  frontend:
    image: lets-chat-frontend
    container_name: lets-chat-frontend
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - test
    depends_on:
      - backend

networks:
  test:

volumes:
  back-notused:
  db-data:

